### ISSUE TITLE
CLI not working

### ISSUE THREAD

**Issue by rstacruz** [millermedeiros/mdoc#49]
```
 →  mdoc
env: node\r: No such file or directory
```

Using node v4.1.0 in OSX v10.11. Not sure what's causing this.

**Comment by eddiemonge** [comment]
Do you have the npm folder in your path?

**Comment by rstacruz** [comment]
I installed using `-g` in this case.

**Comment by eddiemonge** [comment]
Ok. Still, do you have the npm folder in your path? Can you run any other globally installed npm binary?

**Comment by rstacruz** [comment]
Yep.

**Comment by rstacruz** [comment]
i think this is because bin/mdown has CRLF endings, which don't behave properly on linux and osx.

**Comment by eddiemonge** [comment]
It works properly on my OSX so I don't think thats the reason.

**Comment by rstacruz** [comment]
Hmm... if you `npm install mdoc` you'll get CRLF line endings, according to VIM.

**Comment by eddiemonge** [comment]
Possibly but that wouldn't prevent it from running. Have you tried removing it and installing it again?

Is the folder returned by: `ls -al $(npm -g --get prefix)`
in the list thats returned by: `echo $PATH`
?

Does this return anything: `ls -al $(npm -g --get prefix)/bin/mdoc`

**Comment by millermedeiros** [comment]
it's definitely the DOS filetype, seen this happen before in other projects.. the `#!/usr/bin/env node` is not interpreted properly because of the `\r` (it's considered as part of the executable name)

**Comment by millermedeiros** [comment]
ha!, this problem happened before on mdoc as well :P https://github.com/millermedeiros/mdoc/issues/18

**Comment by SandroMartis** [comment]
Same here :(

**Comment by DanielSundberg** [comment]
I get the same thing here, using Powershell on Windows 8.1:

node .\buildDocs.js
C:\Code\Coreweb\CoreInsats\Source\InsatsrapportWeb\Frontend\docs\buildDocs.js:1
(function (exports, require, module, __filename, __dirname) { ??r
                                                              ^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

<code>
require('mdoc').run({
    inputDir: '.',
    outputDir: './static/docs'
});

</code>

**Comment by gbaumgart** [comment]
same here
