### ISSUE TITLE
globals.converter._dispatch is not a function

### ISSUE THREAD

**Issue by brunoshine** [millermedeiros/mdoc#50]
Hi,

I've created a folder and added the examples\basic files to it and `npm install mdoc`. When I run `node build.js` I get the following errors:

```
$ node build.js
  Converting files...
C:\temp\node_modules\mdoc\node_modules\showdown\dist\showdown.js:1540
  text = globals.converter._dispatch('githubCodeBlocks.before', text, options);
                           ^

TypeError: globals.converter._dispatch is not a function
    at C:\temp\node_modules\mdoc\node_modules\showdown\dist\showdown.js:1540:28
    at makeHtml [as parseMdown] (C:\temp\node_modules\mdoc\node_modules\showdown\dist\showdown.js:881:50)
    at Parser.getDescription (C:\temp\node_modules\mdoc\src\js\parser.js:86:17)
    at Parser.getTocData (C:\temp\node_modules\mdoc\src\js\parser.js:61:31)
    at Parser.parseDoc (C:\temp\node_modules\mdoc\src\js\parser.js:19:20)
    at C:\temp\node_modules\mdoc\src\js\writter.js:85:43
    at Object.exports.processFile (C:\temp\node_modules\mdoc\src\js\pathProcessor.js:94:39)
    at C:\temp\node_modules\mdoc\src\js\writter.js:84:23
    at Array.forEach (native)
    at Writter.processDoc (C:\temp\node_modules\mdoc\src\js\writter.js:78:37)
```

I'm on Windows Server 2012 R2 64Bits with node v4.1.2.

Any thoughts on this?

thanks,
Bruno

**Comment by ChristianGrech** [comment]
+1 even when trying to build the example/basic 

Using Windows 10

**Comment by Kreozot** [comment]
Yeah. It's the problem of the new version of showdown (1.3.0). I'll change package.json to use exactly previous version of it and write an issue to showdown developers. Thank you for the report!

**Comment by Kreozot** [comment]
Done.

**Comment by Kreozot** [comment]
And here is the fix! Thanks to @tivie!
